#!/bin/bash

if [ "$1" ]; then
    PROJECT=$1
fi

if [ -z "${PROJECT}" ]; then
    echo "Please set PROJECT variable"
    exit 1
fi

echo Creating $PROJECT

mkdir src
mkdir test

cd src
mkdir $PROJECT
cd $PROJECT
dotnet new classlib
cd ../../

cd test
mkdir $PROJECT.Test
cd $PROJECT.Test
dotnet new xunit
dotnet add reference ../../src/$PROJECT
cd ../../

dotnet new sln
dotnet sln add src/$PROJECT
dotnet sln add test/$PROJECT.Test

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
echo $SCRIPT_DIR

cp -a $SCRIPT_DIR/dotnet-files/. .

git init
git add .
git commit -m "Initial commit"

