#!/bin/bash

if [ "$1" ]; then
    PROJECT=$1
fi

if [ -z "${PROJECT}" ]; then
    echo "Please set PROJECT variable"
    exit 1
fi

echo Creating $PROJECT

mkdir $PROJECT
cd $PROJECT

mkdir src
mkdir test

npm init -y

npm pkg set scripts.build="tsc"
npm pkg set scripts.test="mocha --require ts-node/register test/**.ts test/**/**.ts test/**/**/**.ts"

npm i @types/aws-lambda
npm i @types/chai
npm i @types/mocha
npm i chai
npm i mocha
npm i ts-node

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
echo $SCRIPT_DIR

cp -a $SCRIPT_DIR/ts-project-files/. .

cd ../
echo "cd $PROJECT && npm run test" > test-$PROJECT.sh
chmod 744 test-$PROJECT.sh


